# Generated by Django 5.2.6 on 2025-10-01 19:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drivers', '0002_initial'),
        ('trips', '0001_initial'),
        ('vehicles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tripbooking',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tripbooking',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trip_assignments', to='drivers.driverprofile'),
        ),
        migrations.AddField(
            model_name='tripbooking',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trip_vehicle', to='vehicles.vehicle'),
        ),
    ]
