# Generated by Django 5.2.6 on 2025-10-27 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tripbooking',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
