# Generated by Django 5.2.6 on 2025-10-01 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DriverProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_number', models.CharField(max_length=50, unique=True)),
                ('experience_years', models.PositiveIntegerField(default=0)),
                ('driver_type', models.CharField(choices=[('with_vehicle', 'With Vehicle'), ('without_vehicle', 'Without Vehicle')], max_length=20)),
                ('is_available', models.BooleanField(default=True)),
            ],
        ),
    ]
